version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\FFMediaToolkit\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/radek41-3uj048yghh6h
  api_key:
    secure: N4Ceb4PGYD3hKN+N2ZkaXtocmrZeUb4jBrFLr/tvSzc=
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: GbbjpgH0WOltQC1EMAdCU4sNJNf8isdSHMm2L5NNdbkx9HRqr+upKcPf6C1S5wa6
  on:
    branch: master
    appveyor_repo_tag: true